import pandas as pd
treatments_data = [
    {'Treatment_ID': 'Y1', 'Waste_Item': 'Paper', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 1.4270046, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y2', 'Waste_Item': 'Paper', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 1.5121828, 'Treatment_Cost': 1000.0},
    {'Treatment_ID': 'Y3', 'Waste_Item': 'Paper', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.096969806, 'Treatment_Cost': -200.0},
    {'Treatment_ID': 'Y4', 'Waste_Item': 'Paper', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Burning', 'Emission_Factor': 1.6045562, 'Treatment_Cost': 0.0},
    {'Treatment_ID': 'Y5', 'Waste_Item': 'Paper', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Emission_Factor': 1.8941032, 'Treatment_Cost': 300.0},
    {'Treatment_ID': 'Y6', 'Waste_Item': 'Paper', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 2.5272223, 'Treatment_Cost': 400.0},
    {'Treatment_ID': 'Y7', 'Waste_Item': 'Cardboard', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 1.8311121, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y8', 'Waste_Item': 'Cardboard', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 1.612536, 'Treatment_Cost': 1000.0},
    {'Treatment_ID': 'Y9', 'Waste_Item': 'Cardboard', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 4.8095221, 'Treatment_Cost': 400.0},
    {'Treatment_ID': 'Y10', 'Waste_Item': 'Cardboard', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Emission_Factor': 3.6076679, 'Treatment_Cost': 300.0},
    {'Treatment_ID': 'Y11', 'Waste_Item': 'Cardboard', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Burning', 'Emission_Factor': 2.4673562, 'Treatment_Cost': 0.0},
    {'Treatment_ID': 'Y12', 'Waste_Item': 'Cardboard', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.13406205, 'Treatment_Cost': -200.0},
    {'Treatment_ID': 'Y13', 'Waste_Item': 'Plastic', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 2.3799497, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y14', 'Waste_Item': 'Plastic', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.093376204, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y15', 'Waste_Item': 'Plastic', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Burning', 'Emission_Factor': 2.4421563, 'Treatment_Cost': 0.0},
    {'Treatment_ID': 'Y16', 'Waste_Item': 'Plastic', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Emission_Factor': 0.11001912, 'Treatment_Cost': 300.0},
    {'Treatment_ID': 'Y17', 'Waste_Item': 'Plastic', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 0.15137911, 'Treatment_Cost': 400.0},
    {'Treatment_ID': 'Y18', 'Waste_Item': 'Plastic', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.32484773, 'Treatment_Cost': -300.0},
    {'Treatment_ID': 'Y19', 'Waste_Item': 'Glass', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 0.029362056, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y20', 'Waste_Item': 'Glass', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.011295458, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y21', 'Waste_Item': 'Glass', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Burning', 'Emission_Factor': 0.20755625, 'Treatment_Cost': 0.0},
    {'Treatment_ID': 'Y22', 'Waste_Item': 'Glass', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Emission_Factor': 0.0, 'Treatment_Cost': 300.0},
    {'Treatment_ID': 'Y23', 'Waste_Item': 'Glass', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 0.0048642436, 'Treatment_Cost': 400.0},
    {'Treatment_ID': 'Y24', 'Waste_Item': 'Glass', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.0094020212, 'Treatment_Cost': -100.0},
    {'Treatment_ID': 'Y25', 'Waste_Item': 'Metal Scrap', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.0062589514, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y26', 'Waste_Item': 'Metal Scrap', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 0.033904942, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y27', 'Waste_Item': 'Metal Scrap', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.062741046, 'Treatment_Cost': -1000.0},
    {'Treatment_ID': 'Y28', 'Waste_Item': 'Household Waste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 1.2460356, 'Treatment_Cost': 1000.0},
    {'Treatment_ID': 'Y29', 'Waste_Item': 'Household Waste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.74235224, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y30', 'Waste_Item': 'Household Waste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 1.3054325, 'Treatment_Cost': 400.0},
    {'Treatment_ID': 'Y31', 'Waste_Item': 'Household Waste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Burning', 'Emission_Factor': 1.3354462, 'Treatment_Cost': 0.0},
    {'Treatment_ID': 'Y32', 'Waste_Item': 'Household Waste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Emission_Factor': 0.97663096, 'Treatment_Cost': 300.0},
    {'Treatment_ID': 'Y33', 'Waste_Item': 'Gypsump Plasterboard', 'Category': 'Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.0035980898, 'Treatment_Cost': -500.0},
    {'Treatment_ID': 'Y34', 'Waste_Item': 'Gypsump Plasterboard', 'Category': 'Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.035293422, 'Treatment_Cost': 800.0},
    {'Treatment_ID': 'Y35', 'Waste_Item': 'Sludge', 'Category': 'Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.68407718, 'Treatment_Cost': 1000.0},
    {'Treatment_ID': 'Y36', 'Waste_Item': 'Sludge', 'Category': 'Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 2.3036841, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y37', 'Waste_Item': 'Sludge', 'Category': 'Hazardous Waste', 'Treatment': 'Energy Recovery', 'Emission_Factor': 2.3036841, 'Treatment_Cost': 2000.0},
    {'Treatment_ID': 'Y38', 'Waste_Item': 'Paint', 'Category': 'Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.09514224, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y39', 'Waste_Item': 'Paint', 'Category': 'Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 3.6305226, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y40', 'Waste_Item': 'Paint', 'Category': 'Hazardous Waste', 'Treatment': 'Energy Recovery', 'Emission_Factor': 3.6305226, 'Treatment_Cost': 2500.0},
    {'Treatment_ID': 'Y41', 'Waste_Item': 'Wood', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.08890813, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y42', 'Waste_Item': 'Wood', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 1.4786935, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y43', 'Waste_Item': 'Wood', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Burning', 'Emission_Factor': 1.5953562, 'Treatment_Cost': 0.0},
    {'Treatment_ID': 'Y44', 'Waste_Item': 'Wood', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Emission_Factor': 0.10456916, 'Treatment_Cost': 300.0},
    {'Treatment_ID': 'Y45', 'Waste_Item': 'Wood', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 0.14411984, 'Treatment_Cost': 400.0},
    {'Treatment_ID': 'Y46', 'Waste_Item': 'Wood', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Energy Recovery', 'Emission_Factor': 1.9432214, 'Treatment_Cost': 2000.0},
    {'Treatment_ID': 'Y47', 'Waste_Item': 'Wood', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.051146157, 'Treatment_Cost': -300.0},
    {'Treatment_ID': 'Y48', 'Waste_Item': 'Cement', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.007101107, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y49', 'Waste_Item': 'Cement', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.0035980898, 'Treatment_Cost': -200.0},
    {'Treatment_ID': 'Y50', 'Waste_Item': 'Cement', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 0.54191804, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y51', 'Waste_Item': 'Concrete', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.0062589516, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y52', 'Waste_Item': 'Concrete', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.004379848, 'Treatment_Cost': -100.0},
    {'Treatment_ID': 'Y53', 'Waste_Item': 'Wool', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.0062589514, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y54', 'Waste_Item': 'Wool', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.032774278, 'Treatment_Cost': -300.0},
    {'Treatment_ID': 'Y55', 'Waste_Item': 'Biowaste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Emission_Factor': 0.664828, 'Treatment_Cost': 300.0},
    {'Treatment_ID': 'Y56', 'Waste_Item': 'Biowaste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Industrial Composting', 'Emission_Factor': 0.28482961, 'Treatment_Cost': 500.0},
    {'Treatment_ID': 'Y57', 'Waste_Item': 'Biowaste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Anaerobic Digestion', 'Emission_Factor': 0.33502074, 'Treatment_Cost': 1000.0},
    {'Treatment_ID': 'Y58', 'Waste_Item': 'Biowaste', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 0.55695052, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y59', 'Waste_Item': 'Electronic Waste', 'Category': 'Hazardous Waste', 'Treatment': 'Open Burning', 'Emission_Factor': 0.89122624, 'Treatment_Cost': 0.0},
    {'Treatment_ID': 'Y60', 'Waste_Item': 'Electronic Waste', 'Category': 'Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.11764956, 'Treatment_Cost': 1000.0},
    {'Treatment_ID': 'Y61', 'Waste_Item': 'Electronic Waste', 'Category': 'Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 0.19471437, 'Treatment_Cost': 400.0},
    {'Treatment_ID': 'Y62', 'Waste_Item': 'Electronic Waste', 'Category': 'Hazardous Waste', 'Treatment': 'Recycle', 'Emission_Factor': 0.34607495, 'Treatment_Cost': -1500.0},
    {'Treatment_ID': 'Y63', 'Waste_Item': 'Other Hazardous Waste', 'Category': 'Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 2.5239282, 'Treatment_Cost': 2000.0},
    {'Treatment_ID': 'Y64', 'Waste_Item': 'Other Hazardous Waste', 'Category': 'Hazardous Waste', 'Treatment': 'Energy Recovery', 'Emission_Factor': 2.5239282, 'Treatment_Cost': 2500.0},
    {'Treatment_ID': 'Y65', 'Waste_Item': 'Other Hazardous Waste', 'Category': 'Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Emission_Factor': 0.18600296, 'Treatment_Cost': 1000.0},
    {'Treatment_ID': 'Y66', 'Waste_Item': 'Textile', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Emission_Factor': 1.6655581, 'Treatment_Cost': 1500.0},
    {'Treatment_ID': 'Y67', 'Waste_Item': 'Textile', 'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Emission_Factor': 1.1652431, 'Treatment_Cost': 400.0},
]
treatments_df = pd.DataFrame(treatments_data)

transport_data = [
    {'Mode': 'Tossa motor', 'Emission_per_ton': 0.002061, 'Max_Capacity': 0.5, 'Cost_per_ton': 0.0},
    {'Mode': 'Pickup', 'Emission_per_ton': 0.002118, 'Max_Capacity': 3.5, 'Cost_per_ton': 0.0},
    {'Mode': 'Medium-duty truck', 'Emission_per_ton': 0.000597, 'Max_Capacity': 7.5, 'Cost_per_ton': 0.0},
    {'Mode': 'Heavy-duty truck', 'Emission_per_ton': 0.000248, 'Max_Capacity': 16.0, 'Cost_per_ton': 0.0},
]
transport_df = pd.DataFrame(transport_data)

locations_data = [
    {'Facility_ID': 'TPA001', 'Location': 'PPLI Cileungsi, Jawa Barat', 'Latitude': -6.47, 'Longitude': 106.92},
    {'Facility_ID': 'TPA002', 'Location': 'TPA Sarimukti, Jawa Barat', 'Latitude': -6.8, 'Longitude': 107.35},
    {'Facility_ID': 'TPA003', 'Location': 'PLTSa Bantar Gebang, Bekasi', 'Latitude': -6.35, 'Longitude': 107.0},
    {'Facility_ID': 'TPA004', 'Location': 'TPA Bantar Gebang, Bekasi', 'Latitude': -6.34, 'Longitude': 106.99},
    {'Facility_ID': 'TPA005', 'Location': 'TPA Supit Urang, Malang', 'Latitude': -7.98, 'Longitude': 112.58},
    {'Facility_ID': 'TPA006', 'Location': 'TPA Benowo, Surabaya', 'Latitude': -7.22, 'Longitude': 112.63},
    {'Facility_ID': 'TPA007', 'Location': 'PT. Unilever Indonesia collaboration with PT Trias Sentosa Sidoarjo', 'Latitude': -7.36, 'Longitude': 112.73},
]
locations_df = pd.DataFrame(locations_data)

facility_capacity_data = [
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Facility_ID': 'TPA002', 'Capacity': 1500000.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Facility_ID': 'TPA003', 'Capacity': 100000.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Facility_ID': 'TPA007', 'Capacity': 2000.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Facility_ID': 'TPA004', 'Capacity': 2555000.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Facility_ID': 'TPA005', 'Capacity': 182500.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Energy Recovery', 'Facility_ID': 'TPA003', 'Capacity': 100000.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Industrial Composting', 'Facility_ID': 'TPA005', 'Capacity': 180000.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Anaerobic Digestion', 'Facility_ID': 'TPA006', 'Capacity': 365000.0},
    {'Category': 'Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Facility_ID': 'TPA001', 'Capacity': 10000.0},
    {'Category': 'Hazardous Waste', 'Treatment': 'Incineration', 'Facility_ID': 'TPA001', 'Capacity': 50000.0},
    {'Category': 'Hazardous Waste', 'Treatment': 'Recycle', 'Facility_ID': 'TPA001', 'Capacity': 5000.0},
    {'Category': 'Hazardous Waste', 'Treatment': 'Energy Recovery', 'Facility_ID': 'TPA001', 'Capacity': 5000.0},
]
facility_capacity_df = pd.DataFrame(facility_capacity_data)

max_prop_data = [
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Max_Proportion': 0.1},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Incineration', 'Max_Proportion': 0.05},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Recycle', 'Max_Proportion': 0.15},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Burning', 'Max_Proportion': 1.0},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Open Dump', 'Max_Proportion': 0.7},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Unsanitary Landfill', 'Max_Proportion': 0.16},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Energy Recovery', 'Max_Proportion': 0.01},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Industrial Composting', 'Max_Proportion': 0.01},
    {'Category': 'Non-Hazardous Waste', 'Treatment': 'Anaerobic Digestion', 'Max_Proportion': 0.01},
    {'Category': 'Hazardous Waste', 'Treatment': 'Sanitary Landfill', 'Max_Proportion': 0.15},
    {'Category': 'Hazardous Waste', 'Treatment': 'Incineration', 'Max_Proportion': 0.8},
    {'Category': 'Hazardous Waste', 'Treatment': 'Recycle', 'Max_Proportion': 0.08},
    {'Category': 'Hazardous Waste', 'Treatment': 'Energy Recovery', 'Max_Proportion': 0.08},
]
max_prop_df = pd.DataFrame(max_prop_data)

facility_rules = {'TPA001': {'Category': ['Hazardous Waste'], 'Treatment': ['Recycle', 'Sanitary Landfill', 'Incineration', 'Energy Recovery',]}, 'TPA002': {'Category': ['Non-Hazardous Waste'], 'Treatment': ['Sanitary Landfill']}, 'TPA003': {'Category': ['Non-Hazardous Waste'], 'Treatment': ['Incineration', 'Energy Recovery']}, 'TPA004': {'Category': ['Non-Hazardous Waste'], 'Treatment': ['Open Dump']}, 'TPA005': {'Category': ['Non-Hazardous Waste'], 'Treatment': ['Unsanitary Landfill']}, 'TPA006': {'Category': ['Non-Hazardous Waste'], 'Treatment': ['Anaerobic Digestion']}, 'TPA007': {'Category': ['Non-Hazardous Waste'], 'Treatment': ['Recycle']}}
